# docker-compose for windows-specific details for running aquarium

version: "3.6"
services:
  db:
    volumes:
      - ./docker/mysql_init/:/docker-entrypoint-initdb.d/
    command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON --server-id=1
