# Development docker-compose file for aquarium
#
# Extends the base docker-compose.yml file with details for the development
# environment.
#
# See the file docker-compose.yml for details on changing or resetting the 
# database.
#

version: "3.6"
services:
  app:
    build:
      context: .
      target: basebuilder
    image: basebuilder
    command: ["development"]
    volumes:
      - .:/aquarium
      - ./docker/aquarium/database.yml:/aquarium/config/database.yml
      - ./docker/aquarium/aquarium.rb:/aquarium/config/initializers/aquarium.rb
      - ./docker/aquarium/development.rb:/aquarium/config/environments/development.rb
  db:
    environment:
      MYSQL_DATABASE: development
      MYSQL_USER: aquarium
      MYSQL_PASSWORD: aSecretAquarium
      MYSQL_ROOT_PASSWORD: aSecretAquarium

  krill:
    image: basebuilder
    command: ["development"]

  web:
    volumes:
      - ./docker/nginx.development.conf:/etc/nginx/conf.d/development.conf:ro
