# Docker compose file for development aquarium, which uses docker NAT, a mysql database container,
# and a fake s3 container alongside the normal krill and web services.
#
# In order to run a development aquarium with all required containers, the following steps are required:
# 0. optionally to start from fresh db: sudo rm -rf docker/db/*
# 1. copy this file to aquarium/docker-compose.yml
# 2. copy aquarium/config/dev-docker-database.yml to aquarium/config/database.yml
# 3. copy aquarium/config/initializers/dev-docker-aquarium.rb to aquarium/config/initializers/aquarium.rb
# 4. run 'docker-compose build'
# 5. run 'docker-compose up'

version: "3.6"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/mysql_init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: development
      MYSQL_USER: aquarium
      MYSQL_PASSWORD: aSecretAquarium
      MYSQL_ROOT_PASSWORD: aSecretAquarium
    networks:
     - aquarium_net

  krill:
    build: 
      context: .
    entrypoint: ["/aquarium/aquarium-entrypoint.sh"]
    command: ["krill", "development"]
    networks:
     - aquarium_net
    ports:
      - "3500:3500"
    depends_on:
      - db
      - web

  s3:
    build: .
    command: fakes3 -r /mnt/s3 -p 10001
    volumes:
      - ./docker/s3:/mnt/s3
    ports:
      - "10001:10001"
    networks:
     - aquarium_net

  web:
    build:
      context: .
    entrypoint: ["/aquarium/aquarium-entrypoint.sh"]
    command: ["web", "development"]
    environment:
      - AWS_ACCESS_KEY_ID="" 
      - AWS_SECRET_ACCESS_KEY="" 
      - AWS_REGION=""
    volumes:
      - ./docs:/aquarium/docs
      - ./app:/aquarium/app
      - ./config:/aquarium/config
      - ./db:/aquarium/db
      - ./lib:/aquarium/lib
      - ./log:/aquarium/log
      - ./script:/aquairum/script
      - ./spec:/aquarium/spec
      - ./test:/aquairum/test
    networks:
      - aquarium_net
    ports:
      - "3000:3000"
    depends_on:
      - db
      - s3

networks:
  aquarium_net:
